# Site settings
title: Владислав Миронов Web Developer
description: CV VM Frontend Developer
#baseurl: "cv" # the subpath of your site, e.g. /blog
url: ""
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Владислав Миронов
user_title: WEB разработчик
user_description: Я WEB разработчик c творческими навыками. Люблю структуру и заостряю внимание на каждой детали интерфейса.

email: vmironov16@gmail.com

resume_link: https://drive.google.com/file/d/1nJgM9PB7nt-4z59-TS8cS-U1pUWh52Ih/view?usp=sharing

social_link__tel: tel:+79991554016
social_link__email: mailto:vmironov16@gmail.com
social_link__vk: https://vk.com/vladislavmironov
social_link__tg: https://t.me/vmironov16
social_link__whatsapp: https://wa.me/79991554016
social_link__github: https://github.com/vmironov16
social_link__skype: skype:live:mibookprogtx?call


footer_text: < Владислав Миронов / Web - разработчик >

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
